### ISSUE TITLE
Simplify FHEPayment

### ISSUE THREAD

**Issue by jatZama** [zama-ai/fhevm-backend#189]
The question is should we use this contract only for FHEGas price? This is still unclear since we are waiting ZWS to decide on how to handle Payment for FHE operations. If it is totaally offchain we might have issues with composability if some handles point to nothing.

**Comment by immortal-tofu** [comment]
The idea is to:
- Remove the PaymentContract and PaymentContract calls from TFHEExecutor
- Extends TFHEExecutor and do one of the following:
  - Calls to `FHEGasMonitoring.sol` which is dedicated to monitor gas consumption and revert it reach a threshold.
  - Directly store and monitor gas consumption in the TFHEExecutor contract.

**Comment by jatZama** [comment]
> The idea is to:
> 
> * Remove the PaymentContract and PaymentContract calls from TFHEExecutor
> * Extends TFHEExecutor and do one of the following:
>   
>   * Calls to `FHEGasMonitoring.sol` which is dedicated to monitor gas consumption and revert it reach a threshold.
>   * Directly store and monitor gas consumption in the TFHEExecutor contract.

This is almost surely impossible, since both TFHEExecutor and FHEPayment are already just below the smart contract size limit. So we need two separate contracts here, unfortunately.

**Comment by immortal-tofu** [comment]
Ok ok so good for FHEGasMonitoring.sol 👍

**Comment by immortal-tofu** [comment]
And also we'll remove payment library from fhevm

**Comment by immortal-tofu** [comment]
Specified in https://github.com/zama-ai/fhevm-backend/issues/198
